name: CI CD Pipeline

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2



  test:
    runs-on: ubuntu-latest
    needs: build  # Ensure that the "build" job has completed before running tests
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8  

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run tests
        run: pytest
